import type { Metadata } from "next";
import localFont from "next/font/local";

import Navbar from "@/components/ui/nav-bar/nav-bar";

import CustomProvider from "@/providers/provider";

import "./globals.css";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <CustomProvider>
                    <Navbar />
                    {children}
                </CustomProvider>
            </body>
        </html>
    );
}
